# Generated by Django 5.0.3 on 2024-03-14 02:22

#importing modules 
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

#defining a migration class
class Migration(migrations.Migration):
# initial migration flag to True.
    initial = True

# Dependencies for this migration.
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
# Operations for migration.
    operations = [
        migrations.CreateModel(
            name="BidderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                # setting verbose name for the model.
                "verbose_name": "Bidder",
                 # Setting verbose name plural for the model
                "verbose_name_plural": "Bidders",
                # Setting custom database table name for the model.
                "db_table": "bidder",
                # Defining ordering for querysets of this model.
                "ordering": ["first_name", "last_name"],
            },
        ),
    ]
